import { Schema } from 'mongoose';

import { defineUnscopedCollection } from '../../db/collections';
import { newPublicId } from '../../utils/identifiers';
import { STAFF_ROLES, type StaffRole } from './console.collections';

/**
 * The Trust & Safety audit trail (§13.1's insider-abuse row: "RBAC, just-in-time access,
 * append-only audit, dual review for exports"; §13.2).
 *
 * **A separate collection from `audit_events`, and the reason is structural rather than
 * tidiness.** That one is tenant-scoped: every row belongs to one application, which is
 * right for a trail a tenant reads about its own configuration. A staff read spans every
 * tenant at once, so filing it there would force a choice between two wrong answers —
 * pick one tenant and the trail is incomplete, or write a row per tenant touched and every
 * customer's trail fills with operator activity generated by somebody else.
 *
 * So this is where privileged activity is recorded, and it is UNSCOPED for the same reason
 * the staff roster is: staff act across tenants by definition, and there is no tenant to
 * scope the row by.
 *
 * Without it a cross-tenant read is unauditable, which is the one thing §13.1 says a
 * privileged surface must not be: "personal privilegiado sigue siendo un riesgo" is a
 * residual risk you can only bound if you can reconstruct what was looked at.
 *
 * **Nothing here may carry case material or a subject's identity.** An action, the
 * operator, the roles they held at the time, and at most the id of one application. The
 * trail of who looked at what must not itself become a copy of what they looked at.
 *
 * Append-only by construction: nothing in this module updates or deletes.
 */

export const STAFF_AUDIT_ACTIONS = [
  /** Listed application standing across tenants. */
  'staff.applications.read',
  /** Read the escalated queue across tenants. */
  'staff.escalated.read',
  /** Read the platform metrics. */
  'staff.metrics.read',
  /** Read the dead-letter queue across tenants. */
  'staff.deadletter.read',
  /** Moved one application's standing — the most consequential write on the surface. */
  'staff.standing.changed',
] as const;
export type StaffAuditAction = (typeof STAFF_AUDIT_ACTIONS)[number];

export interface StaffAuditEventDocument {
  staffAuditId: string;
  action: StaffAuditAction;
  actorOxyUserId: string;
  /**
   * The roles the operator held when they acted, copied rather than joined.
   *
   * A trail that read the roster at query time would answer "what may they do NOW", and
   * the question during an investigation is "what were they entitled to THEN" — which
   * changes the moment a role is revoked, exactly when the trail matters most.
   */
  roles: StaffRole[];
  /** The application acted on, when the action names one. Never a case or a person. */
  applicationId: string | null;
  occurredAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

const staffAuditEventSchema = new Schema<StaffAuditEventDocument>(
  {
    staffAuditId: { type: String, required: true, unique: true },
    action: { type: String, required: true, enum: STAFF_AUDIT_ACTIONS },
    actorOxyUserId: { type: String, required: true },
    roles: { type: [String], required: true, enum: STAFF_ROLES, default: [] },
    applicationId: { type: String, default: null },
    occurredAt: { type: Date, required: true },
  },
  { timestamps: true, collection: 'staff_audit_events' },
);

/** The investigator's question: what did this operator do, recently. */
staffAuditEventSchema.index({ actorOxyUserId: 1, occurredAt: -1 });
/** And its mirror: who has been looking at this application. */
staffAuditEventSchema.index({ applicationId: 1, occurredAt: -1 });

export const staffAuditEvents = defineUnscopedCollection(
  'StaffAuditEvent',
  staffAuditEventSchema,
  {
    why: 'Staff act across every tenant, so a trail of their activity has no tenant to be scoped by.',
  },
);

export interface StaffAuditRecord {
  readonly action: StaffAuditAction;
  readonly actorOxyUserId: string;
  readonly roles: readonly StaffRole[];
  readonly applicationId?: string;
}

/**
 * Appends one privileged-activity row.
 *
 * Deliberately NOT best-effort, unlike a refused ingress: a staff read that could not be
 * recorded must fail rather than proceed unrecorded. The trail is the only control §13.1
 * offers against insider abuse, and a surface that quietly serves cross-tenant data when
 * its audit write fails is a surface with no control at all.
 */
export async function appendStaffAuditEvent(record: StaffAuditRecord): Promise<string> {
  const staffAuditId = newPublicId('auditEvent');
  const now = new Date();

  await staffAuditEvents.insertOne({
    staffAuditId,
    action: record.action,
    actorOxyUserId: record.actorOxyUserId,
    roles: [...record.roles],
    applicationId: record.applicationId ?? null,
    occurredAt: now,
    createdAt: now,
    updatedAt: now,
  });

  return staffAuditId;
}
