import { Router } from 'express';

import { ApiError } from '../../http/apiError';
import { isPublicId } from '../../utils/identifiers';
import { appendAuditEvent } from '../audit/audit.collection';
import {
  requestCredentialId,
  requestTenant,
  requireServiceCredential,
} from '../tenancy/serviceCredentialAuth';
import { findCaseView } from './case.service';

/**
 * `GET /v1/cases/{id}` (§10.2) — the application reads back its own case.
 *
 * This is the ACCESS half of §15.3's "audit events for ingress and access", and
 * the reason the audit row is written on a HIT and not on a miss: a 404 is
 * indistinguishable from "belongs to another tenant" by design, so auditing it
 * would fill one tenant's trail with rows generated by another tenant's probing.
 * What is worth recording is that a credential successfully read a case.
 *
 * What comes back is a projection, not the document — see `findCaseView` for
 * which fields are deliberately withheld and why. There is no case SEARCH here
 * and there will not be: an application may look up a case it was given the id
 * of, and the reviewer-facing surface is a different caller class entirely,
 * where "nobody chooses the case they review" applies.
 */
export const casesRouter: Router = Router();

casesRouter.get(
  '/cases/:caseId',
  requireServiceCredential('crowdsource:cases:read'),
  async (request, response) => {
    const caseId = request.params.caseId;
    if (typeof caseId !== 'string' || !isPublicId('case', caseId)) {
      throw new ApiError('not_found', 'No such case.');
    }

    const tenant = requestTenant(request);
    const view = await findCaseView(tenant, caseId);
    if (!view) {
      throw new ApiError('not_found', 'No such case.');
    }

    await appendAuditEvent(tenant, {
      action: 'case.read',
      actorCredentialId: requestCredentialId(request),
      caseId: view.caseId,
    });

    response.status(200).json({
      caseId: view.caseId,
      status: view.status,
      subject: view.subject,
      policy: view.policy,
      taxonomyVersion: view.taxonomyVersion,
      allegationCodes: view.allegationCodes,
      reportCount: view.reportCount,
      sensitivityClass: view.sensitivityClass,
      currentRevision: view.currentRevision,
      /** §10.2: the case AND its decision. Null until a jury has reached one. */
      decision: view.decision,
      createdAt: view.createdAt.toISOString(),
      updatedAt: view.updatedAt.toISOString(),
    });
  },
);
