import { Router } from 'express';

import { ApiError } from '../../http/apiError';
import { isPublicId } from '../../utils/identifiers';
import { appendAuditEvent } from '../audit/audit.collection';
import {
  requestCredentialId,
  requestTenant,
  requireServiceCredential,
} from '../tenancy/serviceCredentialAuth';
import { decisions } from './decision.collection';
import { decisionView } from './decision.service';

/**
 * `GET /v1/decisions/{id}` (§10.2) — one revision of one outcome.
 *
 * §10.2 words it as "obtener una revisión concreta de decisión", and the
 * emphasis is the point: a decision id names a REVISION, not a case. A
 * superseded revision stays readable here forever, which is half of §9.9's
 * "conserva el historial completo" — the other half is `supersedesDecisionId` on
 * the response, which chains backwards from the decision in force (returned by
 * `GET /v1/cases/{id}`) through every revision that preceded it.
 *
 * There is no LIST of decisions and no search. An application reads a decision
 * it was handed the id of, by webhook or by reading its own case; enumerating
 * them would be a moderation-history export nobody asked for, and the scope that
 * authorises this is `crowdsource:cases:read` because a decision is part of the
 * record of a case rather than a resource of its own.
 *
 * The audit row is written on a HIT and not on a miss, for the reason
 * `cases.routes.ts` gives: a 404 is deliberately indistinguishable from
 * "belongs to another tenant", so auditing misses would fill one tenant's trail
 * with rows generated by another tenant's probing.
 */
export const decisionsRouter: Router = Router();

decisionsRouter.get(
  '/decisions/:decisionId',
  requireServiceCredential('crowdsource:cases:read'),
  async (request, response) => {
    const decisionId = request.params.decisionId;
    if (typeof decisionId !== 'string' || !isPublicId('decision', decisionId)) {
      throw new ApiError('not_found', 'No such decision.');
    }

    const tenant = requestTenant(request);
    const stored = await decisions.findOne(tenant, { decisionId });
    if (!stored) {
      throw new ApiError('not_found', 'No such decision.');
    }

    await appendAuditEvent(tenant, {
      action: 'decision.read',
      actorCredentialId: requestCredentialId(request),
      caseId: stored.caseId,
    });

    response.status(200).json(decisionView(stored));
  },
);
